// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyEuxdTMWuV0I18yONOna6ZY_lPDZw2gQ',
    appId: '1:345925378611:web:80c11a469539ba0f06f946',
    messagingSenderId: '345925378611',
    projectId: 'rebottle-4c3de',
    authDomain: 'rebottle-4c3de.firebaseapp.com',
    storageBucket: 'rebottle-4c3de.firebasestorage.app',
    measurementId: 'G-CQBE10R8L5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq6HKlFc7z1bSowWuCGR6H75Hiy_57EM4',
    appId: '1:345925378611:android:440eee84124b3d2006f946',
    messagingSenderId: '345925378611',
    projectId: 'rebottle-4c3de',
    storageBucket: 'rebottle-4c3de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGNQZGkLbCLCFQjwdWdCtC_pkG1zpCnTU',
    appId: '1:345925378611:ios:9d809d4ef5dd6e7f06f946',
    messagingSenderId: '345925378611',
    projectId: 'rebottle-4c3de',
    storageBucket: 'rebottle-4c3de.firebasestorage.app',
    iosBundleId: 'com.example.rebottle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGNQZGkLbCLCFQjwdWdCtC_pkG1zpCnTU',
    appId: '1:345925378611:ios:9d809d4ef5dd6e7f06f946',
    messagingSenderId: '345925378611',
    projectId: 'rebottle-4c3de',
    storageBucket: 'rebottle-4c3de.firebasestorage.app',
    iosBundleId: 'com.example.rebottle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyEuxdTMWuV0I18yONOna6ZY_lPDZw2gQ',
    appId: '1:345925378611:web:68f8b1300079f79106f946',
    messagingSenderId: '345925378611',
    projectId: 'rebottle-4c3de',
    authDomain: 'rebottle-4c3de.firebaseapp.com',
    storageBucket: 'rebottle-4c3de.firebasestorage.app',
    measurementId: 'G-8Z46MN32SE',
  );

}